### ISSUE TITLE
Not able to save order statuse inside the module page

### ISSUE THREAD

**Issue by Freakshows** [coingate/opencart-plugin#2]
I am using coingate200-opencart.ocmod for OC 2.3.0.2, and module is working ok, except that it will not save the statuses inside the module config page.
Error log floods these messages when saving the config page:

```
2017-02-26 18:45:06 - PHP Notice:  Undefined variable: coingate_completed_order_status_id in /xxxxxx/admin/view/template/payment/coingate.tpl on line 248
2017-02-26 18:45:06 - PHP Notice:  Undefined variable: coingate_refunded_order_status_id in /xxxxxx/admin/view/template/payment/coingate.tpl on line 267
```

**Comment by rytisbitcoin** [comment]
Hello,

I have freshly installed OpenCart and CoinGate plugin, and was not able to recreate this issue. Are you using vqmod or any other plugins?

**Comment by Freakshows** [comment]
Hello
Yes i am of course using vqmod and other extensions, it is a live shop. Is there anyone at all that are using just a plain standard opencart installation for a live shop? :)

Do you have any idea on what **type** of extension that maybe could conflict with this module, just so i know on where to start problem solving?

**Comment by rytisbitcoin** [comment]
The most likely culprits would be plugins modifying checkout, order statuses, or payment methods. It could also happen if you use a custom theme which changes these elements.

**Comment by Freakshows** [comment]
Thank you, for now all coingate plugins is disabled on all my webshops until i find out whats causing this.
Funny thing is that these are migrated webshops from oc2.1.0.2 to oc2.3.0.1 with the exact same config and extensions installed, that worked fine on 2.1.0.2 but not on 2.3.0.2
